/* Data-driven bilingual events. Every level has 20 unconditional common
 * events plus its rank's 15 stories. Five recent IDs are excluded.
 * Costs are validated again when a choice is made; every story has a free exit.
 */
'use strict';
const WorldEvents=[];
const EC=(de,en,effect={})=>({label:BI(de,en),effect});
function addWorldEvent(id,range,title,text,choices,requires=null){WorldEvents.push({id,min:range[0],max:range[1],title,text,choices,requires});}
const ALL_LEVELS=[1,Infinity];
const PROD=(multiplier,duration)=>({kind:'production',multiplier,duration});
const MOOD=(value,duration)=>({kind:'mood',value,duration});
const DEF=(multiplier,duration)=>({kind:'defense',multiplier,duration});

// Twenty common stories remain eligible even in a small, impoverished settlement.
addWorldEvent('travelling_tinker',ALL_LEVELS,BI('🛠️ Der wandernde Kesselflicker','🛠️ The travelling tinker'),BI('Ein Handwerker bietet an, verschlissene Geräte auszubessern.','A craftsman offers to repair worn tools.'),[EC('Werkzeuge überholen','Repair the tools',{cost:{gold:35},buff:PROD(1.15,6)}),EC('Nur Erfahrungen austauschen','Exchange advice',{renown:1})]);
addWorldEvent('muddy_road',ALL_LEVELS,BI('🌧️ Versunkene Wege','🌧️ Muddy roads'),BI('Regen hat die Wege aufgeweicht. Die Fuhrleute bitten um Material.','Rain has softened the roads. Carters ask for repair materials.'),[EC('Wege befestigen','Reinforce the roads',{cost:{wood:12,stone:5},renown:2}),EC('Umwege hinnehmen','Accept the detour',{buff:PROD(.9,5)})]);
addWorldEvent('village_fair',ALL_LEVELS,BI('🎪 Ein kleiner Jahrmarkt','🎪 A village fair'),BI('Fahrende Händler möchten auf dem Dorfplatz ihre Stände öffnen.','Travelling merchants want to set up stalls in the square.'),[EC('Standgebühren erheben','Charge stall fees',{gain:{gold:30},hap:-2}),EC('Freien Eintritt gewähren','Offer free admission',{buff:MOOD(1,5)})]);
addWorldEvent('lost_wagon',ALL_LEVELS,BI('🛞 Der herrenlose Wagen','🛞 The abandoned wagon'),BI('Vor dem Tor steht ein Wagen. Ein Siegel verrät seinen Besitzer.','A wagon stands outside the gate. Its seal identifies the owner.'),[EC('Den Besitzer benachrichtigen','Notify the owner',{renown:2,follow:{id:'wagon_owner',delay:6}}),EC('Nutzbares Holz bergen','Salvage the timber',{gain:{wood:15},renown:-1})]);
addWorldEvent('guild_petition',ALL_LEVELS,BI('📜 Bitte der Handwerker','📜 A craftsmen’s petition'),BI('Die Bewohner wünschen sich einen arbeitsfreien Nachmittag.','The residents ask for an afternoon off.'),[EC('Die Pause gewähren','Grant the break',{buff:PROD(.9,3),hap:6}),EC('Auf Termine verweisen','Insist on the deadlines',{hap:-3})]);
addWorldEvent('young_messenger',ALL_LEVELS,BI('✉️ Ein junger Bote','✉️ A young messenger'),BI('Ein erschöpfter Bote bittet um Unterstützung auf seiner Reise.','An exhausted messenger asks for help on the road.'),[EC('Verpflegung mitgeben','Provide provisions',{cost:{food:8},renown:2,follow:{id:'messenger_return',delay:8}}),EC('Den sicheren Weg zeigen','Show a safe route',{renown:1})]);
addWorldEvent('song_of_castle',ALL_LEVELS,BI('🎵 Das Lied von deiner Burg','🎵 A song about your castle'),BI('Eine Sängerin bietet an, vom Leben in deinem Lehen zu erzählen.','A singer offers to tell stories of life in your fief.'),[EC('Eine Aufführung bezahlen','Pay for a performance',{cost:{gold:25},buff:MOOD(2,5)}),EC('Geschichten der Bewohner sammeln','Collect the villagers’ stories',{renown:1})]);
addWorldEvent('boundary_dispute',ALL_LEVELS,BI('⚖️ Streit am Grenzstein','⚖️ A boundary dispute'),BI('Zwei Familien streiten um einen alten Weg. Du sollst vermitteln.','Two families dispute an old path. They ask you to mediate.'),[EC('Einen Vermesser bezahlen','Hire a surveyor',{cost:{gold:20},hap:4,renown:1}),EC('Den Weg gemeinsam nutzen lassen','Make the path shared',{hap:1})]);
addWorldEvent('cold_night',ALL_LEVELS,BI('❄️ Eine kalte Nacht','❄️ A cold night'),BI('Kälte dringt in die Unterkünfte. Die Bewohner brauchen Brennholz.','Cold seeps into the homes. Residents need firewood.'),[EC('Holz verteilen','Distribute firewood',{cost:{wood:15},hap:4}),EC('Gemeinschaftsräume öffnen','Open communal rooms',{buff:MOOD(-1,4)})]);
addWorldEvent('small_inheritance',ALL_LEVELS,BI('🪙 Ein kleines Vermächtnis','🪙 A small inheritance'),BI('Ein verstorbener Kaufmann hat dem Lehen einige Münzen hinterlassen.','A late merchant has left a few coins to the fief.'),[EC('Der Schatzkammer zuführen','Add it to the treasury',{gain:{gold:35}}),EC('An Bedürftige verteilen','Distribute it to the needy',{hap:5,renown:2})]);
addWorldEvent('late_supplies',ALL_LEVELS,BI('📦 Verspätete Lieferung','📦 A late delivery'),BI('Ein Lieferant bietet eine kleine Entschädigung für verspätete Waren.','A supplier offers compensation for a late shipment.'),[EC('Material annehmen','Accept materials',{gain:{wood:8,stone:4}}),EC('Den Vertrag verlängern','Extend the contract',{renown:2})]);
addWorldEvent('town_cleaning',ALL_LEVELS,BI('🧹 Frühjahrsputz','🧹 A village clean-up'),BI('Abfälle sammeln sich an den Wegen. Die Gemeinde schlägt einen Putztag vor.','Waste is collecting along the paths. The community proposes a clean-up.'),[EC('Helfer bezahlen','Pay helpers',{cost:{gold:20},buff:MOOD(1,6)}),EC('Gemeinsam aufräumen','Clean up together',{buff:PROD(.95,3),hap:2})]);
addWorldEvent('stray_dog',ALL_LEVELS,BI('🐕 Der Hund am Burgtor','🐕 The dog at the gate'),BI('Ein Wachhund folgt den Bewohnern. Mit etwas Futter könnte er bleiben.','A watchdog follows the residents. A little food might persuade it to stay.'),[EC('Den Hund aufnehmen','Adopt the dog',{cost:{food:5},buff:DEF(1.1,8)}),EC('Den Besitzer suchen','Find the owner',{renown:1})]);
addWorldEvent('travelling_judge',ALL_LEVELS,BI('⚖️ Die reisende Richterin','⚖️ The travelling judge'),BI('Eine Richterin bietet an, alte Beschwerden der Bevölkerung zu prüfen.','A judge offers to review old grievances.'),[EC('Die Verhandlungen finanzieren','Fund the hearings',{cost:{gold:40},renown:3,buff:MOOD(1,4)}),EC('Öffentliche Sprechstunde halten','Hold a public audience',{hap:2})]);
addWorldEvent('gambling_table',ALL_LEVELS,BI('🎲 Würfel am Brunnen','🎲 Dice by the well'),BI('Ein Glücksspiel zieht die Bewohner an. Der Veranstalter bietet Gebühren an.','A game of dice draws a crowd. Its organizer offers to pay a fee.'),[EC('Das Spiel besteuern','Tax the game',{gain:{gold:25},hap:-3}),EC('Ein friedliches Turnier veranstalten','Arrange a friendly contest',{hap:3})]);
addWorldEvent('old_map',ALL_LEVELS,BI('🗺️ Eine alte Karte','🗺️ An old map'),BI('Ein Händler besitzt Aufzeichnungen über Wege jenseits deiner Grenzen.','A trader has records of paths beyond your borders.'),[EC('Die Aufzeichnungen erwerben','Buy the records',{cost:{gold:30},renown:3,follow:{id:'map_clue',delay:7}}),EC('Nach den nächsten Wegweisern fragen','Ask about nearby signposts',{renown:1})]);
addWorldEvent('wood_carver',ALL_LEVELS,BI('🪵 Die Holzschnitzerin','🪵 The woodcarver'),BI('Eine Reisende möchte ein kleines Wahrzeichen für dein Lehen schnitzen.','A traveller offers to carve a small landmark for your fief.'),[EC('Holz und Lohn bereitstellen','Provide timber and wages',{cost:{wood:10,gold:15},renown:3}),EC('Eine Vorführung erlauben','Allow a demonstration',{hap:2})]);
addWorldEvent('unexpected_donation',ALL_LEVELS,BI('🎁 Ein Geschenk aus der Ferne','🎁 A gift from afar'),BI('Ein ehemaliger Bewohner schickt etwas für seine alte Heimat.','A former resident sends a gift to their old home.'),[EC('Die Vorräte einlagern','Store the supplies',{gain:{bread:10,wood:5}}),EC('Die Gemeinde beschenken','Share with the community',{hap:5})]);
addWorldEvent('workshop_lessons',ALL_LEVELS,BI('📖 Wissen teilen','📖 Shared knowledge'),BI('Erfahrene Bewohner möchten ihr Handwerk weitergeben.','Experienced residents want to share their skills.'),[EC('Unterrichtsmaterial bezahlen','Pay for teaching materials',{cost:{gold:30},buff:PROD(1.12,7)}),EC('Abendliche Treffen erlauben','Allow evening meetings',{renown:1})]);
addWorldEvent('royal_notice',ALL_LEVELS,BI('👑 Ein königlicher Aushang','👑 A royal notice'),BI('Die Krone sucht zuverlässige Lehen für kommende Aufgaben.','The crown is looking for reliable fiefs for future duties.'),[EC('Eine kleine Gabe senden','Send a small gift',{cost:{gold:35},renown:4}),EC('Die Nachricht öffentlich verlesen','Read the notice aloud',{hap:1})]);

// Rank I: outpost, levels 1–4. Fifteen distinct stories.
const R1=[1,4];
addWorldEvent('r1_roof',R1,BI('🛖 Das undichte Dach','🛖 A leaking roof'),BI('Das erste Gemeinschaftshaus braucht eine Reparatur.','The first communal building needs repairs.'),[EC('Das Dach erneuern','Replace the roof',{cost:{wood:8},hap:5}),EC('Mit Tüchern abdichten','Patch it with cloth',{hap:-1})]);
addWorldEvent('r1_settlers',R1,BI('🧳 Siedler am Weg','🧳 Settlers on the road'),BI('Ein Paar sucht eine neue Heimat und bittet um ein Quartier.','A couple seeks a new home and asks for shelter.'),[EC('Aufnehmen und verpflegen','Welcome and feed them',{cost:{food:12},pop:2}),EC('Weiterreisen lassen','Let them travel on',{renown:-1})]);
addWorldEvent('r1_seed',R1,BI('🌱 Saatgut der Nachbarn','🌱 A neighbour’s seeds'),BI('Ein Bauer bietet einen kleinen Beutel erprobten Saatguts an.','A farmer offers a small bag of reliable seed.'),[EC('Saatgut kaufen','Buy the seed',{cost:{gold:20},gain:{wheat:15}}),EC('Beim Tausch helfen','Help arrange a barter',{gain:{gold:8}})]);
addWorldEvent('r1_campfire',R1,BI('🔥 Abend am Lagerfeuer','🔥 An evening by the fire'),BI('Die junge Gemeinde möchte ihre erste gemeinsame Feier abhalten.','The young community wants its first celebration.'),[EC('Vorräte beisteuern','Contribute supplies',{cost:{wood:5,food:5},buff:MOOD(2,4)}),EC('Geschichten erzählen','Tell stories',{hap:2})]);
addWorldEvent('r1_well',R1,BI('🪣 Ein tieferer Brunnen','🪣 A deeper well'),BI('Die Bewohner könnten den Brunnen mit etwas Material besser sichern.','Residents could reinforce the well with a little material.'),[EC('Den Brunnen einfassen','Line the well',{cost:{wood:8,stone:5},buff:PROD(1.1,6)}),EC('Die vorhandene Einfassung pflegen','Maintain its existing lining',{hap:1})]);
addWorldEvent('r1_apprentice',R1,BI('🧑‍🔧 Die erste Lehrstelle','🧑‍🔧 The first apprenticeship'),BI('Ein junger Handwerker sucht einen Ort, an dem er sich beweisen kann.','A young craftsperson seeks a place to prove their skills.'),[EC('Werkzeug stiften','Donate tools',{cost:{gold:25},pop:1,renown:1}),EC('Eine Empfehlung schreiben','Write a recommendation',{renown:1})]);
addWorldEvent('r1_fence',R1,BI('🪵 Die fehlende Umzäunung','🪵 A missing fence'),BI('Wildtiere streifen nachts zwischen den Hütten umher.','Wild animals roam between the huts at night.'),[EC('Einen Zaun errichten','Erect a fence',{cost:{wood:12},buff:DEF(1.2,8)}),EC('Die Bewohner warnen','Warn the residents',{hap:-2})]);
addWorldEvent('r1_market_scales',R1,BI('⚖️ Ungeeichte Waagen','⚖️ Unchecked scales'),BI('Am Markt stimmen zwei Waagen nicht überein.','Two sets of market scales disagree.'),[EC('Neue Gewichte kaufen','Buy new weights',{cost:{gold:15},renown:2}),EC('Öffentlich nachwiegen','Weigh goods publicly',{hap:1})]);
addWorldEvent('r1_woodpile',R1,BI('🌲 Sturmholz am Weg','🌲 Fallen timber'),BI('Ein umgestürzter Baum blockiert den Zugang zum Lehen.','A fallen tree blocks the road to the fief.'),[EC('Das Holz sorgfältig bergen','Recover the timber',{cost:{gold:10},gain:{wood:20}}),EC('Nur den Weg freiräumen','Clear the path',{gain:{wood:5}})]);
addWorldEvent('r1_bread_test',R1,BI('🍞 Das erste Probebacken','🍞 The first test bake'),BI('Eine Bäckerin möchte ein haltbareres Reisebrot ausprobieren.','A baker wants to try making bread that keeps longer.'),[EC('Zutaten bereitstellen','Provide ingredients',{cost:{flour:5,wood:3},gain:{bread:18}}),EC('Das Rezept notieren','Write down the recipe',{renown:1})]);
addWorldEvent('r1_lanterns',R1,BI('🏮 Licht am Tor','🏮 Light at the gate'),BI('Nächtliche Reisende finden dein Tor nur schwer.','Night travellers struggle to find your gate.'),[EC('Laternen aufstellen','Install lanterns',{cost:{gold:18,wood:4},renown:2}),EC('Ein Signalfeuer erlauben','Allow a signal fire',{cost:{wood:3},hap:2}),EC('Bis zum Morgen warten','Wait until morning')]);
addWorldEvent('r1_herbs',R1,BI('🌿 Die Kräuterkundige','🌿 The herbalist'),BI('Eine Kräuterkundige teilt ihr Wissen gegen eine kleine Gabe.','An herbalist offers advice in exchange for a small gift.'),[EC('Ihre Arbeit unterstützen','Support her work',{cost:{food:5},buff:MOOD(1,6)}),EC('Den Gartenweg zeigen','Show her the garden path',{hap:1})]);
addWorldEvent('r1_names',R1,BI('📛 Namen für die Wege','📛 Naming the paths'),BI('Die Bewohner wollen den ersten Straßen Namen geben.','Residents want to name their first streets.'),[EC('Schilder anfertigen','Make signs',{cost:{wood:5},renown:2}),EC('Die Namen mündlich verkünden','Announce the names',{hap:2})]);
addWorldEvent('r1_rope',R1,BI('🪢 Ein gerissenes Zugseil','🪢 A snapped hauling rope'),BI('Beim Transport ist ein wichtiges Seil gerissen.','An important rope snapped during transport.'),[EC('Ersatz beschaffen','Buy a replacement',{cost:{gold:15},buff:PROD(1.08,5)}),EC('Langsamer weiterarbeiten','Continue more slowly',{buff:PROD(.95,3)})]);
addWorldEvent('r1_first_letter',R1,BI('✉️ Grüße der Nachbarn','✉️ Greetings from neighbours'),BI('Ein benachbartes Lehen erkundigt sich nach deiner jungen Siedlung.','A neighbouring fief asks about your young settlement.'),[EC('Ein Gastgeschenk senden','Send a welcoming gift',{cost:{food:8},renown:3}),EC('Freundlich antworten','Reply warmly',{renown:1})]);

// Rank II: fortified village, levels 5–9.
const R2=[5,9];
addWorldEvent('r2_gate_watch',R2,BI('🛡️ Wachwechsel am Tor','🛡️ Changing the watch'),BI('Die Wachleute schlagen einen verbesserten Dienstplan vor.','The watch proposes a better duty roster.'),[EC('Zusätzliche Ausbildung bezahlen','Pay for extra training',{cost:{gold:50},buff:DEF(1.2,8)}),EC('Den bisherigen Plan beibehalten','Keep the old roster',{hap:-1})]);
addWorldEvent('r2_watermill',R2,BI('⚙️ Ein Vorschlag für die Mühle','⚙️ A millwright’s proposal'),BI('Eine Fachfrau kennt einen Weg, Reibungsverluste zu senken.','A specialist knows how to reduce mechanical friction.'),[EC('Die Umrüstung finanzieren','Fund the adjustment',{cost:{gold:60,wood:10},buff:PROD(1.18,8)}),EC('Den Vorschlag archivieren','File the proposal',{renown:1})]);
addWorldEvent('r2_harvest_festival',R2,BI('🌾 Erntefest des Dorfes','🌾 The village harvest feast'),BI('Die Familien wollen den Ertrag gemeinsam feiern.','Families want to celebrate the season’s work.'),[EC('Ein Festmahl stiften','Sponsor a feast',{cost:{food:25,beer:5},buff:MOOD(3,6),renown:2}),EC('Ein kleines Treffen erlauben','Allow a small gathering',{hap:2})]);
addWorldEvent('r2_bridge',R2,BI('🌉 Die beschädigte Brücke','🌉 The damaged bridge'),BI('Eine Brücke an der Grenze braucht tragfähige Balken.','A bridge at the border needs sound beams.'),[EC('Die Brücke reparieren','Repair the bridge',{cost:{wood:25,stone:15},follow:{id:'bridge_trade',delay:8},renown:2}),EC('Die Furt nutzen','Use the ford',{buff:PROD(.9,6)})]);
addWorldEvent('r2_poachers',R2,BI('🏹 Unerlaubte Jagd','🏹 Unlicensed hunting'),BI('Einwohner haben ohne Erlaubnis im herrschaftlichen Wald gejagt.','Residents have hunted in the lord’s forest without permission.'),[EC('Eine maßvolle Abgabe erheben','Levy a modest fine',{gain:{gold:35},hap:-3}),EC('Die Beute teilen lassen','Let them share the catch',{gain:{meat:12},hap:2})]);
addWorldEvent('r2_merchant_credit',R2,BI('🪙 Vorschuss der Kaufleute','🪙 A merchant advance'),BI('Eine Handelsgruppe bietet Gold für eine kleine Materiallieferung.','A trading group offers gold for a modest shipment.'),[EC('Holz liefern','Supply timber',{cost:{wood:30},gain:{gold:70},renown:1}),EC('Keine Verpflichtung eingehen','Decline the obligation')]);
addWorldEvent('r2_forge_bellows',R2,BI('🔥 Der neue Blasebalg','🔥 A new bellows'),BI('Ein Schmied preist ein zuverlässigeres Werkzeug an.','A smith advertises a more reliable tool.'),[EC('Die Vorführung finanzieren','Fund the demonstration',{cost:{gold:45,iron:5},buff:PROD(1.15,8)}),EC('Bei den alten Werkzeugen bleiben','Keep the old tools',{hap:1})]);
addWorldEvent('r2_border_market',R2,BI('🤝 Markt an der Grenze','🤝 A border market'),BI('Händler bitten um einen friedlichen Handelstag an der Grenze.','Merchants request a peaceful market day at the border.'),[EC('Eine Grenzruhe aushandeln','Negotiate a border truce',{cost:{gold:70},special:'truce',duration:10}),EC('Nur im Dorf handeln lassen','Restrict trade to the village',{gain:{gold:15}})],'enemy');
addWorldEvent('r2_cattle_fever',R2,BI('🐄 Unruhige Herde','🐄 A restless herd'),BI('Ein Viehhüter braucht Hilfe, um die Herde zu versorgen.','A herder needs help tending the animals.'),[EC('Heilmittel beschaffen','Buy remedies',{cost:{gold:40},gain:{cheese:8}}),EC('Die Herde schonen','Rest the herd',{buff:PROD(.92,5)})],'cattle');
addWorldEvent('r2_travelling_mason',R2,BI('🧱 Der reisende Steinmetz','🧱 The travelling mason'),BI('Ein Steinmetz bietet Übungsstunden für die Bautrupps an.','A mason offers lessons to the building crews.'),[EC('Unterricht bezahlen','Pay for lessons',{cost:{gold:45,stone:8},buff:DEF(1.15,10)}),EC('Erfahrungen besprechen','Discuss experience',{renown:1})]);
addWorldEvent('r2_new_families',R2,BI('🏠 Zuzug aus dem Umland','🏠 Families from the countryside'),BI('Drei arbeitswillige Bewohner suchen Schutz im Dorf.','Three willing workers seek shelter in the village.'),[EC('Neuankömmlinge aufnehmen','Welcome the newcomers',{cost:{food:24,gold:15},pop:3}),EC('Wegzehrung wünschen','Wish them a safe journey',{hap:-2})]);
addWorldEvent('r2_brewers_pride',R2,BI('🍺 Stolz der Brauer','🍺 The brewers’ pride'),BI('Die Brauer möchten ihr jüngstes Fass bewerten lassen.','The brewers want their latest barrel judged.'),[EC('Zur Verkostung freigeben','Offer a tasting',{cost:{beer:10},renown:4,hap:3}),EC('Das Fass verkaufen','Sell the barrel',{cost:{beer:10},gain:{gold:45}}),EC('Vorräte behalten','Keep the supplies')],'beer');
addWorldEvent('r2_sentry_tracks',R2,BI('👣 Spuren am Waldrand','👣 Tracks at the forest edge'),BI('Die Torwache hat verdächtige Spuren entdeckt.','The gate watch has found suspicious tracks.'),[EC('Die Wache ausrüsten','Equip the watch',{cost:{gold:35,wood:8},buff:DEF(1.25,6)}),EC('Die Tore früher schließen','Close the gates earlier',{buff:MOOD(-1,4)})]);
addWorldEvent('r2_granary_mice',R2,BI('🐭 Mäuse im Kornspeicher','🐭 Mice in the granary'),BI('Kleine Nager haben einen Weg zu den Vorräten gefunden.','Small rodents have found a way into the supplies.'),[EC('Die Vorräte sichern','Secure the supplies',{cost:{wood:10,gold:15}}),EC('Beschädigte Säcke aussortieren','Discard damaged sacks',{loss:{wheat:10,bread:8}})]);
addWorldEvent('r2_charter',R2,BI('📜 Eine neue Dorfordnung','📜 A village charter'),BI('Die Gemeinde schlägt klare Regeln für gemeinschaftliche Arbeiten vor.','The community proposes clear rules for shared work.'),[EC('Die Ordnung ausarbeiten lassen','Have the charter drafted',{cost:{gold:55},renown:5,buff:MOOD(1,6)}),EC('Bisherige Regeln bestätigen','Confirm existing rules',{hap:1})]);

// Rank III: stone castle, levels 10–19.
const R3=[10,19];
addWorldEvent('r3_cracked_wall',R3,BI('🧱 Risse im Mauerwerk','🧱 Cracks in the masonry'),BI('Eine Inspektion zeigt Reparaturbedarf an den Befestigungen.','An inspection reveals repairs needed in the defenses.'),[EC('Die Schäden reparieren','Repair the damage',{cost:{stone:30,gold:60},buff:DEF(1.12,10)}),EC('Nur die gefährlichsten Stellen sichern','Secure only the worst sections',{buff:DEF(.9,7)})]);
addWorldEvent('r3_crossbow_trials',R3,BI('🎯 Die Armbrustprobe','🎯 Crossbow trials'),BI('Ein Waffenmeister bietet Übungen gegen gepanzerte Ziele an.','A weapon master offers drills against armored targets.'),[EC('Übungsmunition bezahlen','Pay for practice supplies',{cost:{gold:70,wood:15},buff:DEF(1.2,9)}),EC('Seine Erfahrungen anhören','Hear his advice',{renown:2})]);
addWorldEvent('r3_pike_drill',R3,BI('🔱 Geschlossene Reihen','🔱 Close ranks'),BI('Die Ausbilder wollen das Halten einer Pikenformation üben.','The trainers want to practice holding a pike formation.'),[EC('Ein Manöver finanzieren','Fund a maneuver',{cost:{food:30,gold:50},buff:DEF(1.25,8)}),EC('Bei regulären Übungen bleiben','Keep regular drills',{hap:1})],'army');
addWorldEvent('r3_ore_sample',R3,BI('⛓️ Eine vielversprechende Erzprobe','⛓️ A promising ore sample'),BI('Bergleute vermuten eine kleinere Seitenader im erschlossenen Gebiet.','Miners suspect a small side vein in developed land.'),[EC('Die Probe untersuchen','Examine the sample',{cost:{gold:110,wood:15},special:'ironSurvey',amount:180}),EC('Das Risiko vermeiden','Avoid the risk',{gain:{iron:3}})],'iron');
addWorldEvent('r3_quarry_fault',R3,BI('⛏️ Bruchkante im Stein','⛏️ A fault in the quarry'),BI('Eine Felsspalte könnte neues Gestein freigeben, braucht aber Sicherung.','A fissure could expose more stone, but needs securing.'),[EC('Die Kante abstützen','Brace the fault',{cost:{wood:25,gold:80},special:'stoneSurvey',amount:250}),EC('Den Bereich sperren','Close the section',{buff:PROD(.95,5)})],'mine');
addWorldEvent('r3_harvest_tithe',R3,BI('🌾 Der Zehntstreit','🌾 A dispute over the tithe'),BI('Die Bauern bitten nach einer schwierigen Saison um Entlastung.','Farmers ask for relief after a difficult season.'),[EC('Saatgut und Vorräte geben','Provide seed and supplies',{cost:{wheat:20,food:20},buff:MOOD(2,8),renown:3}),EC('Die Forderungen beibehalten','Keep the demands',{gain:{gold:65},hap:-6})],'farms');
addWorldEvent('r3_castle_wedding',R3,BI('💍 Hochzeit auf der Burg','💍 A castle wedding'),BI('Eine Hochzeit könnte die Familien des Lehens zusammenbringen.','A wedding could bring the fief’s families together.'),[EC('Das Fest ausrichten','Host the celebration',{cost:{food:40,beer:15,gold:50},renown:7,buff:MOOD(3,7)}),EC('Eine kleine Feier erlauben','Allow a small celebration',{hap:3})]);
addWorldEvent('r3_master_tanner',R3,BI('🦺 Die Meistergerberin','🦺 The master tanner'),BI('Eine Spezialistin bietet besonders haltbare Lederrüstungen an.','A specialist offers particularly durable leather armor.'),[EC('Rüstungen überarbeiten lassen','Rework armor',{cost:{leatherArmor:8,gold:45},gain:{leatherArmor:10}}),EC('Die Techniken dokumentieren','Document the techniques',{renown:2})]);
addWorldEvent('r3_prisoner_exchange',R3,BI('🤝 Unterhändler am Tor','🤝 An envoy at the gate'),BI('Ein Gegner schlägt eine vorübergehende Entspannung an der Grenze vor.','An enemy proposes a temporary easing of border tensions.'),[EC('Die Verhandlungen unterstützen','Support negotiations',{cost:{gold:130},special:'truce',duration:14,renown:2}),EC('Die Grenzen geschlossen halten','Keep the borders closed',{buff:DEF(1.08,6)})],'enemy');
addWorldEvent('r3_ration_audit',R3,BI('📋 Die Rationsprüfung','📋 A ration audit'),BI('Die Vorratsverwaltung entdeckt unklare Einträge in den Büchern.','Supply officers find unclear entries in the ledgers.'),[EC('Die Buchhaltung ordnen','Reconcile the books',{cost:{gold:60},gain:{bread:25},renown:2}),EC('Mit dem vorhandenen Bestand planen','Plan around existing supplies',{hap:-2})]);
addWorldEvent('r3_stone_art',R3,BI('🗿 Ein Wahrzeichen aus Stein','🗿 A stone landmark'),BI('Ein Bildhauer bietet ein Denkmal für die Leistungen der Gemeinde an.','A sculptor offers a monument to the community’s achievements.'),[EC('Den Auftrag erteilen','Commission the monument',{cost:{stone:40,gold:100},renown:10}),EC('Eine einfache Gedenktafel wählen','Choose a simple plaque',{cost:{wood:8},renown:2}),EC('Den Auftrag vertagen','Postpone the commission')]);
addWorldEvent('r3_siege_engineer',R3,BI('🛠️ Der Belagerungsingenieur','🛠️ The siege engineer'),BI('Ein Ingenieur kennt die Schwachstellen üblicher Befestigungen.','An engineer knows the weak points of common fortifications.'),[EC('Die eigene Burg prüfen lassen','Commission a castle inspection',{cost:{gold:95,stone:15},buff:DEF(1.3,8)}),EC('Seine Skizzen ansehen','Study his sketches',{renown:2})]);
addWorldEvent('r3_dry_fields',R3,BI('☀️ Trockene Äcker','☀️ Dry fields'),BI('Die Feldgräben müssen ausgebessert werden, bevor die Ernte leidet.','Field ditches need repairs before crops suffer.'),[EC('Die Bewässerung reparieren','Repair irrigation',{cost:{wood:20,gold:65},buff:PROD(1.1,7)}),EC('Wasser sparsam verteilen','Ration the water',{buff:PROD(.88,6)})],'farms');
addWorldEvent('r3_merchant_house',R3,BI('🏦 Ein Handelshaus stellt sich vor','🏦 A merchant house arrives'),BI('Ein Handelshaus möchte die Zuverlässigkeit deiner Lieferungen prüfen.','A merchant house wants to test your delivery reliability.'),[EC('Eine Musterlieferung senden','Send a sample shipment',{cost:{bread:25,leatherArmor:2},gain:{gold:160},renown:3,follow:{id:'merchant_return',delay:9}}),EC('Noch keine Zusage machen','Make no commitment')]);
addWorldEvent('r3_veteran_family',R3,BI('🎖️ Familie eines Veteranen','🎖️ A veteran’s family'),BI('Die Familie eines erfahrenen Soldaten sucht ein sicheres Zuhause.','An experienced soldier’s family seeks a safe home.'),[EC('Die Familie aufnehmen','Welcome the family',{cost:{food:30,gold:35},pop:3,renown:3}),EC('Eine Empfehlung mitgeben','Give them a recommendation',{renown:1})]);

// Rank IV: trading town, levels 20–34.
const R4=[20,34];
addWorldEvent('r4_guild_rivalry',R4,BI('🏛️ Streit der Zünfte','🏛️ Rival guilds'),BI('Zwei Zünfte beanspruchen denselben Lieferauftrag.','Two guilds claim the same delivery contract.'),[EC('Einen Ausgleich finanzieren','Fund a settlement',{cost:{gold:160},buff:PROD(1.2,9)}),EC('Die Zünfte selbst verhandeln lassen','Let the guilds negotiate',{buff:PROD(.9,6)})]);
addWorldEvent('r4_river_customs',R4,BI('🛶 Zölle am Fluss','🛶 River tolls'),BI('Ein Flusshändler bietet eine größere Lieferung gegen Materialtausch.','A river trader offers a substantial barter shipment.'),[EC('Material tauschen','Exchange materials',{cost:{stone:40,wood:40},gain:{gold:230},renown:3}),EC('Nur den Anlegeplatz öffnen','Open the landing place',{gain:{gold:40}})]);
addWorldEvent('r4_great_fire',R4,BI('🔥 Funken über den Dächern','🔥 Sparks over the rooftops'),BI('Ein Feuer droht von einem Werkplatz auf Vorräte überzugreifen.','A workshop fire threatens nearby supplies.'),[EC('Löschtrupps bezahlen','Pay firefighting crews',{cost:{gold:130,wood:15},renown:2}),EC('Vorräte in Sicherheit bringen','Evacuate the supplies',{loss:{wood:35,wheat:20},buff:PROD(.9,4)})]);
addWorldEvent('r4_iron_contract',R4,BI('⛓️ Eisen für die Hauptstadt','⛓️ Iron for the capital'),BI('Ein königlicher Einkäufer sucht eine verlässliche Eisenlieferung.','A royal buyer seeks a reliable shipment of iron.'),[EC('Eisen liefern','Deliver iron',{cost:{iron:35},gain:{gold:210},renown:5}),EC('Die Anfrage weitergeben','Refer the request',{renown:1})]);
addWorldEvent('r4_land_registry',R4,BI('🗺️ Das neue Kataster','🗺️ A new land register'),BI('Eine genaue Vermessung könnte Streit und unnötige Wege vermeiden.','A proper survey could avoid disputes and wasted journeys.'),[EC('Vermesser beauftragen','Commission surveyors',{cost:{gold:180},buff:PROD(1.15,12),renown:4}),EC('Alte Aufzeichnungen ergänzen','Update old records',{hap:2})]);
addWorldEvent('r4_food_embargo',R4,BI('🍞 Eine teure Karawane','🍞 An expensive caravan'),BI('Eine verspätete Karawane bietet Lebensmittel zu einem Sonderpreis an.','A delayed caravan offers food at a special price.'),[EC('Die Ladung kaufen','Buy the shipment',{cost:{gold:150},gain:{bread:45,cheese:15}}),EC('Bei eigenen Vorräten bleiben','Rely on existing supplies',{renown:1})]);
addWorldEvent('r4_armorer_order',R4,BI('🛡️ Die Rüstungsmesse','🛡️ An armor fair'),BI('Rüstungshandwerker bieten eine Verarbeitung größerer Materialmengen an.','Armorers offer to process a larger batch of materials.'),[EC('Metallrüstungen bestellen','Commission metal armor',{cost:{iron:15,gold:100},gain:{armor:10}}),EC('Lederrüstungen bestellen','Commission leather armor',{cost:{gold:210},gain:{leatherArmor:15}}),EC('Nur die Ausstellung besuchen','Visit the exhibition',{renown:1})]);
addWorldEvent('r4_mine_supports',R4,BI('⛏️ Sicherung der Stollen','⛏️ Reinforcing the tunnels'),BI('Die Bergleute benötigen Stützen für einen neuen Seitenstollen.','Miners need supports for a new side tunnel.'),[EC('Den Stollen ausbauen','Extend the tunnel',{cost:{wood:45,gold:180},special:'ironSurvey',amount:300}),EC('Den Hauptstollen weiter nutzen','Keep using the main tunnel',{buff:PROD(.95,5)})],'iron');
addWorldEvent('r4_city_delegation',R4,BI('🤝 Gesandte der Städte','🤝 A delegation of towns'),BI('Benachbarte Städte möchten gemeinsame Standards für Handwerk besprechen.','Nearby towns want common standards for craftwork.'),[EC('Die Versammlung ausrichten','Host the assembly',{cost:{gold:140,food:40},renown:12,buff:PROD(1.1,8)}),EC('Schriftlich teilnehmen','Participate by letter',{renown:3})]);
addWorldEvent('r4_veteran_drill',R4,BI('🎖️ Veteranen als Ausbilder','🎖️ Veterans as instructors'),BI('Erfahrene Soldaten bieten eine intensive Ausbildungswoche an.','Veteran soldiers offer an intensive training period.'),[EC('Die Ausbildung finanzieren','Fund the training',{cost:{gold:170,food:35},buff:DEF(1.3,10)}),EC('Erfahrungsberichte sammeln','Collect their accounts',{renown:3})],'army');
addWorldEvent('r4_market_fraud',R4,BI('⚖️ Falsche Warenzeichen','⚖️ Counterfeit trade marks'),BI('Einige Waren tragen gefälschte Zunftzeichen.','Some goods bear counterfeit guild marks.'),[EC('Eine Untersuchung bezahlen','Fund an investigation',{cost:{gold:100},renown:8,hap:4}),EC('Nur die betroffenen Waren sperren','Impound only the affected goods',{loss:{leatherArmor:4,flour:10},hap:-3})]);
addWorldEvent('r4_new_quarter',R4,BI('🏘️ Bewohner aus einer Nachbarstadt','🏘️ Residents from a nearby town'),BI('Fünf Fachkräfte möchten in dein Lehen ziehen.','Five skilled workers wish to move to your fief.'),[EC('Den Umzug unterstützen','Support their move',{cost:{gold:100,food:45},pop:5}),EC('Auf spätere Aufnahme vertrösten','Ask them to return later',{renown:1})]);
addWorldEvent('r4_border_diplomacy',R4,BI('🕊️ Ein Waffenstillstand','🕊️ A proposed truce'),BI('Ein Nachbar zeigt Interesse an einer befristeten Ruhephase.','A neighbour is interested in a temporary ceasefire.'),[EC('Die Verhandlungskosten tragen','Pay negotiation costs',{cost:{gold:240},special:'truce',duration:18}),EC('Nur eine Botschaft senden','Send a message only',{renown:2})],'enemy');
addWorldEvent('r4_bakers_competition',R4,BI('🥖 Wettbewerb der Bäcker','🥖 A bakers’ contest'),BI('Die Bäcker möchten ihr Können auf dem großen Markt zeigen.','Bakers want to demonstrate their skills at the main market.'),[EC('Zutaten und Preisgeld geben','Provide ingredients and prizes',{cost:{flour:30,gold:90},gain:{bread:95},renown:5}),EC('Eine kleine Schau erlauben','Allow a small demonstration',{hap:3})]);
addWorldEvent('r4_royal_engineers',R4,BI('🏰 Königliche Baumeister','🏰 Royal master builders'),BI('Baumeister des Königs wollen die Sicherung deiner Versorgungswege prüfen.','Royal builders offer to inspect your supply-route defenses.'),[EC('Die Prüfung finanzieren','Fund the inspection',{cost:{gold:200,stone:30},buff:DEF(1.25,12),renown:4}),EC('Die vorhandenen Pläne zeigen','Show existing plans',{renown:2})]);

// Rank V: royal fortress, level 35 and above.
const R5=[35,Infinity];
addWorldEvent('r5_royal_visit',R5,BI('👑 Der Besuch des Hofes','👑 A visit from the court'),BI('Eine Abordnung des Hofes will deine Festung besuchen.','A court delegation wishes to visit your fortress.'),[EC('Einen würdigen Empfang geben','Host a grand reception',{cost:{gold:350,food:70,beer:25},renown:25,buff:MOOD(3,10)}),EC('Einen schlichten Empfang wählen','Offer a modest welcome',{renown:4})]);
addWorldEvent('r5_war_council',R5,BI('⚔️ Der Kriegsrat','⚔️ A war council'),BI('Befehlshaber möchten ihre Verteidigungspläne aufeinander abstimmen.','Commanders want to coordinate their defense plans.'),[EC('Ein großes Manöver finanzieren','Fund a major maneuver',{cost:{gold:300,food:60},buff:DEF(1.4,12)}),EC('Berichte schriftlich austauschen','Exchange written reports',{renown:4})],'army');
addWorldEvent('r5_grand_fair',R5,BI('🎪 Die große Handelsmesse','🎪 The grand trade fair'),BI('Fernhändler bieten eine Messe mit zahlreichen Abnehmern an.','Long-distance merchants propose a fair with many buyers.'),[EC('Eine Großlieferung bereitstellen','Provide a bulk shipment',{cost:{leatherArmor:20,crossbow:10},gain:{gold:650},renown:12}),EC('Nur Standplätze verwalten','Manage the stalls only',{gain:{gold:60},hap:2})]);
addWorldEvent('r5_quarry_gallery',R5,BI('🧱 Der tiefe Bruch','🧱 The deep quarry'),BI('Unter einer gesicherten Felskante liegt weiteres nutzbares Gestein.','Usable stone lies beneath a reinforced rock face.'),[EC('Die Erschließung bezahlen','Fund its development',{cost:{gold:300,wood:70},special:'stoneSurvey',amount:600}),EC('Den Zugang dokumentieren','Document the access',{renown:4})],'mine');
addWorldEvent('r5_iron_experts',R5,BI('⛓️ Erzmeister aus der Ferne','⛓️ Master miners from afar'),BI('Spezialisten bieten an, eine tiefer liegende Ader sicher freizulegen.','Specialists offer to expose a deeper vein safely.'),[EC('Die Fachleute beauftragen','Hire the specialists',{cost:{gold:400,wood:60},special:'ironSurvey',amount:450}),EC('Ihre Gutachten aufbewahren','Keep their reports',{renown:3})],'iron');
addWorldEvent('r5_grain_relief',R5,BI('🌾 Hilfe für das Umland','🌾 Relief for the countryside'),BI('Eine benachbarte Gemeinde bittet nach einer Missernte um Hilfe.','A nearby community asks for help after a failed harvest.'),[EC('Vorräte schicken','Send supplies',{cost:{food:100,wheat:40},renown:22,hap:5}),EC('Händler vermitteln','Connect them with merchants',{renown:3})]);
addWorldEvent('r5_fortress_repair',R5,BI('🏰 Die große Instandsetzung','🏰 Major fortress repairs'),BI('Die Festung benötigt eine gründliche Prüfung ihrer tragenden Teile.','The fortress needs a thorough inspection of its structural supports.'),[EC('Alles instand setzen','Carry out full repairs',{cost:{gold:280,stone:80,wood:30},buff:DEF(1.3,15)}),EC('Nur das Nötigste sichern','Secure the essentials',{buff:DEF(.9,8)})]);
addWorldEvent('r5_embassy',R5,BI('🕊️ Gesandtschaft am Hof','🕊️ An embassy at court'),BI('Eine Gesandtschaft könnte für längere Ruhe an einer Grenze sorgen.','An embassy could secure a longer peace along one border.'),[EC('Die Gesandtschaft ausrüsten','Equip the embassy',{cost:{gold:500,food:50},special:'truce',duration:24,renown:8}),EC('Nur Briefe senden','Send letters only',{renown:4})],'enemy');
addWorldEvent('r5_tapestry',R5,BI('🧵 Die Geschichte des Lehens','🧵 The story of the fief'),BI('Künstler möchten die Geschichte deiner Gemeinde festhalten.','Artists want to record the community’s history.'),[EC('Das Werk in Auftrag geben','Commission the work',{cost:{gold:380},renown:25}),EC('Die Erzählungen sammeln lassen','Collect oral histories',{renown:5})]);
addWorldEvent('r5_supply_reform',R5,BI('📦 Neuordnung der Versorgung','📦 Reforming supply management'),BI('Verwalter schlagen eine gemeinsame Planung aller Lieferwege vor.','Administrators propose unified planning of supply routes.'),[EC('Die Reform finanzieren','Fund the reform',{cost:{gold:330,wood:40},buff:PROD(1.25,14)}),EC('Schrittweise abstimmen','Coordinate gradually',{buff:PROD(1.05,5)})]);
addWorldEvent('r5_scholars',R5,BI('📚 Gelehrte in der Festung','📚 Scholars at the fortress'),BI('Gelehrte wollen die Fertigkeiten deiner Handwerker studieren.','Scholars want to study your craftspeople’s techniques.'),[EC('Eine Lehrsammlung einrichten','Establish a teaching collection',{cost:{gold:250,food:35},renown:15,buff:PROD(1.15,12)}),EC('Öffentliche Gespräche erlauben','Allow public discussions',{renown:4,hap:2})]);
addWorldEvent('r5_retired_captain',R5,BI('🎖️ Der alte Hauptmann','🎖️ The retired captain'),BI('Ein erfahrener Hauptmann bietet seine Kenntnisse der Burgverteidigung an.','An experienced captain offers expertise in castle defense.'),[EC('Als Berater verpflichten','Hire him as an adviser',{cost:{gold:280,food:30},buff:DEF(1.35,12)}),EC('Seine Erinnerungen anhören','Listen to his stories',{renown:3})]);
addWorldEvent('r5_great_migration',R5,BI('🧳 Zuzug zur Königsfestung','🧳 Migration to the royal fortress'),BI('Acht Fachkräfte bitten um Aufnahme in deine Festungsstadt.','Eight prospective workers seek admission to the fortress town.'),[EC('Die Aufnahme organisieren','Organize their admission',{cost:{gold:220,food:90},pop:8,renown:5}),EC('Aufnahme für später vormerken','Record them for later admission',{renown:2})]);
addWorldEvent('r5_crown_order',R5,BI('📜 Auftrag der Krone','📜 An order from the crown'),BI('Der Hof benötigt eine Lieferung zeitgemäßer Bewaffnung.','The court needs a shipment of modern armaments.'),[EC('Armbrüste und Piken liefern','Supply crossbows and pikes',{cost:{crossbow:15,pike:20},gain:{gold:800},renown:18}),EC('Den Auftrag höflich ablehnen','Politely decline',{renown:1})]);
addWorldEvent('r5_peoples_council',R5,BI('🏛️ Der Rat der Bewohner','🏛️ The residents’ council'),BI('Eine große Gemeinde braucht verlässliche Mitsprache bei ihren Aufgaben.','A large community needs a dependable voice in shared decisions.'),[EC('Den Rat ausstatten','Support the council',{cost:{gold:240,food:40},buff:MOOD(3,14),renown:12}),EC('Regelmäßige Sprechstunden abhalten','Hold regular public audiences',{hap:4})]);

// Five original IDs remain valid for a saved, unresolved version-6 event.
addWorldEvent('harvest',ALL_LEVELS,BI('🌾 Reiche Ernte','🌾 Bountiful harvest'),BI('Die vorhandenen Felder tragen überraschend gut. Wie nutzt du den Überschuss?','The existing fields yield unexpectedly well. How will you use the surplus?'),[EC('Vorräte einlagern','Store supplies',{gain:{wheat:25,apple:10}}),EC('Auf dem Markt verkaufen','Sell at market',{gain:{gold:80}})],'farms');
addWorldEvent('refugees',ALL_LEVELS,BI('🧳 Flüchtlinge am Tor','🧳 Refugees at the gate'),BI('Zwei Menschen bitten um Schutz und sofortige Verpflegung.','Two people ask for protection and immediate provisions.'),[EC('Tore öffnen','Open the gates',{cost:{food:15},pop:2}),EC('Weiterleiten','Refer them elsewhere',{hap:-3})]);
addWorldEvent('caravan',ALL_LEVELS,BI('🐫 Fernhandelskarawane','🐫 Distant caravan'),BI('Eine Karawane bietet Eisen an oder bittet um Hilfe bei ihrer Weiterreise.','A caravan offers iron or asks for help arranging its onward journey.'),[EC('Eisen kaufen','Buy iron',{cost:{gold:40},gain:{iron:15}}),EC('Eine sichere Route vermitteln','Arrange a safe route',{gain:{gold:20},renown:1})]);
addWorldEvent('fire',ALL_LEVELS,BI('🔥 Feuer im Lager','🔥 Warehouse fire'),BI('Ein Funke hat einen Teil des Holzvorrats entzündet.','A spark has ignited part of the timber stock.'),[EC('Handwerker bezahlen','Pay the craftsmen',{cost:{gold:50}}),EC('Brennende Vorräte aufgeben','Abandon burning supplies',{loss:{wood:35}})],'woodStock');
addWorldEvent('levy',ALL_LEVELS,BI('👑 Forderung der Krone','👑 Royal levy'),BI('Die Krone verlangt eine Sonderabgabe für ihre Aufgaben.','The crown demands a special contribution for its duties.'),[EC('Die Abgabe leisten','Pay the levy',{cost:{gold:80},renown:3}),EC('Um Aufschub bitten','Request a delay',{hap:-5,renown:-1})]);

// Follow-ups are queued by a real prior choice, never selected from thin air.
function followEvent(id,title,text,choices){addWorldEvent(id,[0,Infinity],title,text,choices);WorldEvents.at(-1).followOnly=true;}
followEvent('wagon_owner',BI('🛞 Der Wagenbesitzer kehrt zurück','🛞 The wagon’s owner returns'),BI('Der benachrichtigte Besitzer bedankt sich für deine Ehrlichkeit.','The owner you contacted thanks you for your honesty.'),[EC('Finderlohn annehmen','Accept the reward',{gain:{gold:65}}),EC('Um gutes Wort bitten','Ask for a recommendation',{renown:5})]);
followEvent('messenger_return',BI('✉️ Antwort des Boten','✉️ The messenger’s reply'),BI('Der versorgte Bote bringt einen Dankesbrief und eine kleine Gabe.','The messenger you supplied returns with a letter and a small gift.'),[EC('Die Gabe annehmen','Accept the gift',{gain:{bread:18,gold:20}}),EC('Die Nachricht im Dorf teilen','Share the message',{renown:4,hap:3})]);
followEvent('map_clue',BI('🗺️ Die Karte zahlt sich aus','🗺️ The map proves useful'),BI('Die gekauften Aufzeichnungen weisen einen kürzeren Transportweg aus.','The records you purchased reveal a shorter supply route.'),[EC('Den Weg nutzen','Use the route',{buff:PROD(1.15,8)}),EC('Die Abschrift weitergeben','Share a copy',{gain:{gold:55},renown:2})]);
followEvent('bridge_trade',BI('🌉 Handel über die neue Brücke','🌉 Trade across the repaired bridge'),BI('Über die reparierte Brücke erreicht eine dankbare Karawane dein Lehen.','A grateful caravan reaches your fief across the repaired bridge.'),[EC('Handelsgebühren annehmen','Accept trade fees',{gain:{gold:140}}),EC('Lieferungen bevorzugen','Choose supplies',{gain:{wood:30,iron:12},renown:3})]);
followEvent('merchant_return',BI('🏦 Die bewährte Geschäftsbeziehung','🏦 A proven trading relationship'),BI('Deine Musterlieferung hat überzeugt. Das Handelshaus schickt eine Anerkennung.','Your sample shipment impressed the merchant house. It sends a token of appreciation.'),[EC('Gold annehmen','Accept gold',{gain:{gold:130},renown:3}),EC('Material bevorzugen','Choose materials',{gain:{iron:15,leatherArmor:5}})]);

const EventEngine={
  definition(id){return WorldEvents.find(e=>e.id===id);},
  condition(key,state=S){
    if(!key)return true;
    const predicates={farms:()=>Object.entries(Config.b).some(([k,b])=>b.z==='z-farm'&&state.b[k]>0),mine:()=>World.owned(state).some(r=>r.buildings.quarry>0),iron:()=>World.owned(state).some(r=>r.buildings.iron>0),army:()=>World.unitCount(state.units)>0,enemy:()=>World.enemies(state).length>0,beer:()=>state.b.brew>0,cattle:()=>state.b.dairy>0,woodStock:()=>state.res.wood>0};
    return !!predicates[key]?.();
  },
  eligible(state=S,excludeRecent=true){return WorldEvents.filter(e=>!e.followOnly&&(state.lvl||1)>=e.min&&(state.lvl||1)<=e.max&&this.condition(e.requires,state)&&(!excludeRecent||!state.events.recent.includes(e.id)));},
  check(state=S){
    if(state.paused||Tutorial.active||state.events.pending||state.world.raidPending||state.day<(state.events.nextDay||7))return false;
    const due=state.events.queue.findIndex(e=>e.dueDay<=state.day&&this.definition(e.id));
    let def;
    if(due>=0)def=this.definition(state.events.queue.splice(due,1)[0].id);
    else{const pool=this.eligible(state);if(!pool.length)return false;def=pool[Math.floor(World.random(state)*pool.length)];}
    state.events.pending={id:def.id};state.paused=true;this.render(state.events.pending);Storage.save();return true;
  },
  gains(effect,state=S){return Object.fromEntries(Object.entries(effect.gain||{}).map(([k,n])=>[k,k==='gold'?Math.round(n*(1+(state.upgrades.diplomacy||0)*.08)):n]));},
  canChoose(choice,state=S){
    if(!choice)return false;const e=choice.effect;
    if(!World.canPay(e.cost||{},state))return false;
    if(e.pop&&state.pop.max-state.pop.curr<e.pop)return false;
    if(e.special==='truce'&&!World.enemies(state).length)return false;
    if(e.special==='stoneSurvey'&&!this.condition('mine',state))return false;
    if(e.special==='ironSurvey'&&!this.condition('iron',state))return false;
    return true;
  },
  hint(choice,state=S,lang=I18N.lang){
    const e=choice.effect,parts=[];
    for(const [k,n] of Object.entries(e.cost||{}))parts.push('−'+numberText(n,lang)+' '+(k==='food'?trl('food',lang):SafeT(k,lang)));
    for(const [k,n] of Object.entries(this.gains(e,state)))parts.push('+'+numberText(n,lang)+' '+SafeT(k,lang));
    for(const [k,n] of Object.entries(e.loss||{}))parts.push((lang==='de'?'bis zu −':'up to −')+numberText(n,lang)+' '+SafeT(k,lang));
    for(const [key,label] of [['hap','happiness'],['renown','renown'],['pop','population']])if(e[key])parts.push((e[key]>0?'+':'')+e[key]+' '+trl(label,lang));
    if(e.buff){const b=e.buff;parts.push((b.kind==='mood'?((b.value>0?'+':'')+b.value+' '+trl('happiness',lang)):((Math.round((b.multiplier-1)*100)>0?'+':'')+Math.round((b.multiplier-1)*100)+' % '+(b.kind==='defense'?trl('defense',lang):(lang==='de'?'Produktion':'production'))))+' · '+b.duration+' '+(lang==='de'?'Spieltage':'game days'));}
    if(e.special==='truce')parts.push((lang==='de'?'Angriff eines Nachbarn frühestens in ':'One neighbour cannot attack for ')+e.duration+(lang==='de'?' Spieltagen':' game days'));
    if(e.special==='stoneSurvey'||e.special==='ironSurvey')parts.push('+'+e.amount+' '+SafeT(e.special==='stoneSurvey'?'stone':'iron',lang)+' '+(lang==='de'?'im Boden; kein zusätzlicher Bauplatz':'in deposits; no extra plot'));
    if(e.follow)parts.push((lang==='de'?'Folgegeschichte frühestens in ':'Follow-up after at least ')+e.follow.delay+(lang==='de'?' Spieltagen':' game days'));
    if(Object.keys(e.gain||{}).some(k=>k!=='gold'))parts.push(lang==='de'?'Automatik/Lagergrenzen gelten':'Automation/storage limits apply');
    return parts.join(' · ')||trl('no_changes',lang);
  },
  choose(id,index,state=S){
    const def=this.definition(id),choice=def&&Number.isInteger(index)&&def.choices[index];
    if(state.events.pending?.id!==id||!choice||!this.canChoose(choice,state))return false;
    const effect=choice.effect;World.pay(effect.cost||{},state);
    for(const [k,n] of Object.entries(this.gains(effect,state)))addAmount(state.res,k,n);
    for(const [k,n] of Object.entries(effect.loss||{}))state.res[k]=Math.max(0,roundQty((state.res[k]||0)-n));
    state.renown=Math.max(0,state.renown+(effect.renown||0));state.pop.hap=clamp(state.pop.hap+(effect.hap||0),0,100);state.pop.curr+=effect.pop||0;
    if(effect.buff)state.world.effects.push({...effect.buff,label:def.title,expiresAt:state.day+effect.buff.duration+1});
    if(effect.follow)state.events.queue.push({id:effect.follow.id,dueDay:state.day+effect.follow.delay});
    if(effect.special==='truce'){const r=World.enemies(state).sort((a,b)=>a.enemy.nextRaid-b.enemy.nextRaid)[0];r.enemy.truceUntil=Math.max(r.enemy.truceUntil||0,state.day+effect.duration);r.enemy.warned=false;}
    if(effect.special==='stoneSurvey'||effect.special==='ironSurvey'){
      const key=effect.special==='stoneSurvey'?'quarry':'iron',resource=key==='quarry'?'stone':'iron';
      const r=World.owned(state).find(r=>r.buildings[key]>0);r.deposits[resource]=roundQty(r.deposits[resource]+effect.amount);
    }
    state.events.pending=null;state.events.seen=(state.events.seen||0)+1;
    state.events.recent=[...state.events.recent,id].slice(-5);state.events.nextDay=state.day+10+Math.floor(World.random(state)*7);
    reconcileWorkforce(state);rebalanceMarket(state);enforceStorageLimits(state);World.syncThreat(state);
    World.record(dual(lang=>`${loc(def.title,lang)}: ${loc(choice.label,lang)}.`),'prod',state);
    document.getElementById('event-mask').style.display='none';state.paused=false;lastTickTime=Date.now();UI.update();return true;
  },
  render(pending){
    const def=this.definition(pending.id);if(!def){S.events.pending=null;S.paused=false;document.getElementById('event-mask').style.display='none';return;}
    S.paused=true;document.getElementById('event-title').innerText=loc(def.title);document.getElementById('event-text').innerText=loc(def.text);
    const list=document.getElementById('event-choices');list.innerHTML='';
    for(let i=0;i<def.choices.length;i++){const c=def.choices[i],button=document.createElement('button');button.className='btn';button.disabled=!this.canChoose(c);button.innerHTML=loc(c.label)+'<small>'+this.hint(c)+(button.disabled?' · '+tr('no_afford'):'')+'</small>';button.onclick=()=>this.choose(def.id,i);list.appendChild(button);}
    document.getElementById('event-mask').style.display='flex';Storage.save();
  }
};
